"""init

Revision ID: f4395fc9935f
Revises: 
Create Date: 2026-07-08 00:54:10.385290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4395fc9935f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('messages_chat_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'private_chats', ['chat_id'], ['id'])
    op.add_column('private_chats', sa.Column('last_message', sa.Text(), nullable=True))
    op.alter_column('private_chats', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('private_chats', 'last_event_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'private_chats', 'users', ['user1_id'], ['id'])
    op.create_foreign_key(None, 'private_chats', 'users', ['user2_id'], ['id'])
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'private_chats', type_='foreignkey')
    op.drop_constraint(None, 'private_chats', type_='foreignkey')
    op.alter_column('private_chats', 'last_event_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('private_chats', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('private_chats', 'last_message')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_chat_id_fkey'), 'messages', 'private_chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
